### ISSUE TITLE
Kernel Update Schedule?

### ISSUE THREAD

**Issue by GeorgeHahn** [renesas-rz/rskrza1_bsp_releases#1]
I see that the BSP is currently built on 3.14.79-LTSI. Are there any plans to update to 4.1.17-LTSI?

Thanks!

**Comment by seebe** [comment]
For RZ/A, we're skipping 4.1 and going with 4.9-LTSI. A lot of the drivers are being upstreammed now. Anything upstreamed past 4.9 will be backported into the BSP that will be posted here. The 4.9 BSP will also contain drivers that will not be upstreamed (for one reason or another).

**Comment by GeorgeHahn** [comment]
Thanks for the fast response, it's great to know that this BSP is actively maintained!
